# Generated by Django 3.0.6 on 2020-05-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('district', models.CharField(blank=True, max_length=300, null=True)),
                ('grid_x', models.IntegerField(blank=True, null=True)),
                ('grid_y', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('idn', models.CharField(max_length=200, unique=True)),
                ('date_of_birth', models.DateField()),
                ('date_of_confirm', models.DateField()),
                ('case_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('district', models.CharField(blank=True, max_length=300, null=True)),
                ('grid_x', models.IntegerField(blank=True, null=True)),
                ('grid_y', models.IntegerField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='covidapp.Patient')),
            ],
        ),
    ]
